### ISSUE TITLE
Asset Playback Issues

### ISSUE THREAD

**Issue by gavspav** [roundware/roundware-web-template#22] opened 2022-12-06 22:49 UTC
Again, this could well be user error but......

When I press the play button in the listen screen, I can hear the speaker but there is no mixing of other assets. I think there was before. Skip to next button gives a Remixing Audio:skipping ahead message but nothing happens.

Similarly on mobile (web app again) enabling walking mode does not seem to play assets as I think it did before. It plays the speaker - currently the national anthem - and it does mangle it a bit (speed change?) which is quite pleasing but seems a bit random!

I've tried toggling Autoplay in config.json but I couldn't really tell any difference.
GEO_LISTEN_MODE and AVAILABLE_LISTEN_MODES are set to device. Are these relevant?
AVAILABLE_LISTEN_FILTERS - I think these are for filtering the assets and not applicable to this case. Not sure though.
The speaker volume range is roughly halfway and attenuation set to 10.

**Comment by hburgund** [comment] 2022-12-07 18:56
the joys of the bleeding edge! yes, this did used to work fine, but it seems something in our recent development has caused an issue. will investigate and get back to you. You might have luck with commit 53a6b4c ... lmk if any better as I think the issue was introduced recently with some new WIP stuff.

the "device" settings mean that it behaves differently according to whether you are on mobile or laptop. for mobile, it would default to "walking" mode and for laptop, "map" mode.

But there is an underlying issue here not related to config settings, I believe.

**Comment by gavspav** [comment] 2022-12-07 19:10
I think the version I'm using is just one commit behind that - [This one](https://github.com/roundware/roundware-web-template/commit/ff506945d88cbceff3cb8f7e3a35203b42de21cd)

**Comment by hburgund** [comment] 2022-12-07 20:40
interesting...that commit works for me, but the ones after it don't. let's both make sure we have done `npm install` etc to make sure we have all the right packages installed.

**Comment by gavspav** [comment] 2022-12-07 23:17
Well I did merge that commit with my customised branch and I have made a couple of config changes since so it's not exactly scientific I guess.

**Comment by gavspav** [comment] 2023-02-06 22:47
Any idea if this has been fixed? I tried to update to the newest commit but it broke everything so I am still on [this one](https://github.com/roundware/roundware-web-template/commit/53a6b4c81af8cde5cb0f1271a091280c61bc31ac)

**Comment by gavspav** [comment] 2023-02-07 12:00
On closer inspection whilst this appears to be an asset playback issue the problem might actually lie elsewhere.
I've pointed the config file to a different project and it does play old clips correctly in that project.
But.....if I record new clips (via the microphone), they don't playback with the play button.

**Comment by hburgund** [comment] 2023-02-07 14:30
I haven't been able to reproduce this issue in the newer code; afaict, this was a temporary break that got fixed, but I'm not 100% sure! Can you have a look at a deploy of recent code and let me know if you experience the same issues?

https://roundware.surge.sh/

What platform are you testing on? Device? Browser? I've mainly been testing on my laptop and mobile is definitely more touchy, so that also might be a factor here.

**Comment by gavspav** [comment] 2023-02-07 14:47
Just doing this as we speak! I've cloned the latest repo from [here](https://github.com/shreyas-jadhav/roundware-web-template) and it appears to work so far!
I can't seem to point it to our server when deploying though. Has the config system changed? I copied config.json across but it hasn't worked.

**Comment by gavspav** [comment] 2023-02-07 15:36
Ok update - I think the issue is something to do with our settings in the admin panel. Tags or something?
If I deploy the code and it points to https://prod.roundware.com/api/2 uploading assets and playing them back in walking mode or geomode seems to work fine. However if I change it to our server at https://audio-server.co.uk/api/2 then recorded clips do not play back in walking mode/geo mode.
I don't know really where to start looking for the problem but I did notice before that some older clips would play back in these modes but newly recorded clips would not. Also when I look at the envelope for these newly recorded clips geo listen is not enabled. I do not know how to turn this on in the admin panel as I have to enter something in the device box and nothing I enter seems to work - it fails to save. Any ideas?

**Comment by gavspav** [comment] 2023-02-08 16:26
Hmm still no nearer working out what is going on and I've tried alot of things! Our project [here](https://chb.surge.sh/listen) - if you press the play button at the bottom to start the roundware mixer it does play some assets as expected. However the site [here](https://audioville.surge.sh/listen) when you press play, none of the assets are mixed. Looking at the js console it just doesn't seem to find any audio assets to play. I've compared the audio assets in both projects and I can't see what the problem might be. Additionally I discovered that it is only the old assets that play even in the first site I linked too. If you record a new clip, it will not playback if you press the mixer playback button. This behaviour is identical in walking mode as well. Any ideas how to troubleshoot this? I'm going round and round in circles! I won't post the link to our admin page here but it is the same as when I last sent it to you!

**Comment by hburgund** [comment] 2023-02-08 16:49
So to be clear, the issues you are having are specific to your deploy, not likely overall RW issues since my deploy is working for you in similar circumstances?

If so, sounds like it might be a data issue since you tried your same config, but pointing to my server and all was OK, yes? If we narrow it down to data, it'll be easier to figure out...I will have a look later today, but lmk...

**Comment by gavspav** [comment] 2023-02-08 17:49
Yes it looks that way. I didn't realise as things seemed to stop working at a certain point. I assumed it was due to updating the web template but now it looks like it was something our end all along.

No freshly recorded clips on either of our deploments will play back in the mixer but on [this one](https://chb.surge.sh/listen) some of the older clips - dating from two years ago - will play back.

I've tried to look for a pattern - something that is consistently different between the assets which play and the ones which don't but I can't see anything.

**Comment by gavspav** [comment] 2023-02-08 18:24
Aha - think I've sussed it. Partly at least. There was no Audio Track on our second deployment.
I can't remember setting one up on the first one to be honest! Or ever encountering one - but maybe I forgot or accidentally deleted it.
In any case, clips seem to be playing back as expected now.
So it looks like this is a non issue - feel free to close it.

**Comment by hburgund** [comment] 2023-02-08 22:25
Amazing! Yes, Audiotracks are required for the assets to play in the stream as they dictate the various parameters which the assets playback using. You need at least one, but if you want to potentially have more than one asset playing simultaneously in the stream, you can make more audiotracks, with different params if you want...

I'll close this, but can open again if still trouble...

**Closed by hburgund** 2023-02-08 22:25 UTC
